### GENERAL SETTINGS ###

# Site settings
title: Nerdtank Backgrounds
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: "/profiles"

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#141414" #"#F70031"
  primary_rgb: "211,84,0" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#d35400" #"#33004D"
  link: "#d35400"
  link_hover: "#d35400"
  footer_heading: "#141414"
  footer_content: "#141414"


### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: dribbble
    url:
  - title: facebook
    url:
  - title: twitter
    url:
  - title: instagram
    url:
  - title: tumblr
    url:

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - Profile - !setprofilebg
    - Rank    - !setrankbg
    - LevelUp - !setlevelbg
email: hello@solidtheme.com
tel: +34 8493-4893
